// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./../../src/components/counter.vue')['default']
    Header: typeof import('./../../src/components/header/index.vue')['default']
    HeaderBreadcrumb: typeof import('./../../src/components/header/breadcrumb.vue')['default']
    HeaderLogo: typeof import('./../../src/components/header/logo.vue')['default']
    HeaderMenu: typeof import('./../../src/components/header/menu.vue')['default']
    Hello: typeof import('./../../src/components/hello.vue')['default']
    'IMaterialSymbols:close': typeof import('~icons/material-symbols/close')['default']
    'IMdi:accountBoxMultiple': typeof import('~icons/mdi/account-box-multiple')['default']
    'IMdi:accountEditOutline': typeof import('~icons/mdi/account-edit-outline')['default']
    'IMdi:formatIndentDecrease': typeof import('~icons/mdi/format-indent-decrease')['default']
    'IMdi:formatIndentIncrease': typeof import('~icons/mdi/format-indent-increase')['default']
    Menu: typeof import('./../../src/components/menu.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./../../src/components/tabs.vue')['default']
  }
}
